[internal]
exten => 1001,1,Set(RECFN=/recordings/${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}-${CALLERID(num)}-to-1001-${UNIQUEID}.wav)
 same  => n,MixMonitor(${RECFN},b)
 same  => n,Dial(PJSIP/1001,30)
 same  => n,StopMixMonitor()
 same  => n,Hangup()

exten => 1002,1,Set(RECFN=/recordings/${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}-${CALLERID(num)}-to-1002-${UNIQUEID}.wav)
 same  => n,MixMonitor(${RECFN},b)
 same  => n,Dial(PJSIP/1002,30)
 same  => n,StopMixMonitor()
 same  => n,Hangup()

; 휴대폰 테스트용 내선(새로 추가)
exten => 2001,1,Set(RECFN=/recordings/${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}-${CALLERID(num)}-to-2001-${UNIQUEID}.wav)
 same  => n,MixMonitor(${RECFN},b)
 same  => n,Dial(PJSIP/2001,30)
 same  => n,StopMixMonitor()
 same  => n,Hangup()

exten => 2002,1,Set(RECFN=/recordings/${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}-${CALLERID(num)}-to-2002-${UNIQUEID}.wav)
 same  => n,MixMonitor(${RECFN},b)
 same  => n,Dial(PJSIP/2002,30)
 same  => n,StopMixMonitor()
 same  => n,Hangup()

; 테스트용 에코(600번)
exten => 600,1,Set(RECFN=/recordings/${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}-echo-${UNIQUEID}.wav)
 same  => n,MixMonitor(${RECFN},b)
 same  => n,Answer()
 same  => n,Echo()
 same  => n,StopMixMonitor()
 same  => n,Hangup()
