[global]
type=global
user_agent=Asterisk-Docker

; ---------- Transport ----------
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

; 휴대폰이 접근 가능한 호스트 IP로 Contact/SDP 광고
external_signaling_address=[IP_ADDRESS] #ex)192.168.137.xxx
external_signaling_port=5060
external_media_address=[IP_ADDRESS] #ex)192.168.137.xxx

; local_net은 제거(도커 브리지 대역을 로컬로 잡으면 172.19.0.2를 광고하는 문제 발생)
; local_net=


; ---------- Endpoint 1001 ----------
[1001]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw
auth=1001-auth
aors=1001
direct_media=no

; NAT/브리지 환경 안정화
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[1001-auth]
type=auth
auth_type=userpass
username=1001
password=pass1001

[1001]
type=aor
max_contacts=1
remove_existing=yes


; ---------- Endpoint 1002 ----------
[1002]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw
auth=1002-auth
aors=1002
direct_media=no

; NAT/브리지 환경 안정화
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[1002-auth]
type=auth
auth_type=userpass
username=1002
password=pass1002

[1002]
type=aor
max_contacts=1
remove_existing=yes


; ---------- Endpoint 2001 (Phone) ----------
[2001]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw
auth=2001-auth
aors=2001
direct_media=no

; NAT/브리지 환경 안정화
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[2001-auth]
type=auth
auth_type=userpass
username=2001
password=pass2001

[2001]
type=aor
max_contacts=1
remove_existing=yes


; ---------- Endpoint 2002 (Phone) ----------
[2002]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw
auth=2002-auth
aors=2002
direct_media=no

; NAT/브리지 환경 안정화
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[2002-auth]
type=auth
auth_type=userpass
username=2002
password=pass2002

[2002]
type=aor
max_contacts=1
remove_existing=yes
